Merged SideBarLayoutContext and PaneMenulItem
neolution-ch/react-pattern-ui pull request #37
Opened 2023-09-13 13:22 UTC by severinoAmmirati

- Removed `SideBarLayoutContext` as can be replaced by `PanelSideBarLayoutContext`
- Merged `PaneMenulItem` into `PanelItem`

2023-09-13 15:07 UTC, manni497 commented
@severinoAmmirati As discussed, please merge also PanelSideBarContext and PanelSideBarMenuContext :D

2023-09-14 19:52 UTC, manni497 requested changes

2023-09-15 08:13 UTC, severinoAmmirati commented on src/lib/Layout/PanelSideBarLayout/PanelSideBar/Definitions/PanelSideBarMenuItem.ts
> +  icon?: IconProp;
Icons are optional in both left and right sidebar, and seems that no exception are thrown
![image](https://github.com/neolution-ch/react-pattern-ui/assets/116279805/38e69bd6-8bcc-444c-ab06-da80777b0a34)

2023-09-15 09:14 UTC, severinoAmmirati commented on src/lib/Layout/PanelSideBarLayout/PanelSideBar/Definitions/PanelSideBarMenuItem.ts
> +  icon?: IconProp;
@manni497 Exception added

2023-09-15 09:15 UTC, severinoAmmirati commented on src/lib/Layout/PanelSideBarLayout/PanelSideBar/PanelSideBarItem.tsx
> +  const { depth = 0, children, LinkRenderer, onClick, toggledItemIds = [] } = props;
@manni497 Renamed as item

2023-09-15 09:15 UTC, severinoAmmirati commented on src/lib/Layout/PanelSideBarLayout/PanelSideBar/PanelSideBarItem.tsx
> +                {children.icon && <FontAwesomeIcon icon={children.icon as IconProp} className="me-2" />}
@manni497 Not needed, removed

2023-09-15 09:16 UTC, severinoAmmirati commented on src/lib/Layout/PanelSideBarLayout/PanelSideBar/Context/PanelSideBarContext.tsx
> +  //const firstActivePanel = globalItems.find((x) => x.children?.find((y) => y.active)) ?? globalItems.find((x) => x.id);
@manni497 Logic improved, let me know if it's good for you

2023-09-18 07:43 UTC, manni497 approved these changes

2023-09-18 09:59 UTC, neotob approved these changes

2023-09-18 10:00 UTC, merged